#Template #1: General project. Test it using existing `platformio.ini`.

language: python
python:
    - "2.7"

sudo: false

cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=src/main.cpp

install:
    - pip install -U platformio
    - export PLATFORMIO_BUILD_FLAGS="-D ENABLE_SONOFF"
script:
    - platformio ci --project-conf=platoformio.ini
