
language: python
python:
  - "2.7"

sudo: false

env:
  - PLATFORMIO_CI_SRC=src/main.cpp

install:
  - pip install -U platformio

script:
  - python deploy.py

deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file_glob: true
  file: sonoff-danimtb_*.zip
  skip_cleanup: true
  on:
    tags: true
